### ISSUE TITLE
Meridian: Measure

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#23]
ETA: 2023-08-31

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-station/spark-api/issues/41
- [x] IE: Measure function
- [ ] https://github.com/Meridian-IE/measure-service/issues/1
- [ ] https://github.com/filecoin-station/spark-api/issues/42
```

_This milestone will follow [Quality criteria](https://www.notion.so/Quality-criteria-7132527056b24bdca269bd08c0bfea94?pvs=21)_
