### ISSUE TITLE
Make SPs participate in attestation protocol

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#26]
```[tasklist]
### Tasks
- [ ] Write spec for signature chain header (all protocols, start with http)
- [ ] Ensure chains can’t be reused (include hash of unique request identifier)
- [ ] Create GH issue on [Boost repo](https://github.com/filecoin-project/boost) + follow up where requested / as necessary
```

**Comment by bajtos** [comment]
IPFS spec discussion: https://github.com/ipfs/specs/pull/431

**Comment by patrickwoodhead** [comment]
I will take a stab at working in the feedback to the spec
