### ISSUE TITLE
Meridian: Evaluate

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#33]
```[tasklist]
### Tasks
- [x] Await round start
- [x] Fetch preprocessed measurements
- [x] Evaluate
- [x] Submit to IE contract
```

**Comment by juliangruber** [comment]
Will be closed by https://github.com/filecoin-station/spark-evaluate/pull/1
