### ISSUE TITLE
Station: Soft launch as Rewards Technical Preview

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#37]
ETA: 2023-09-15

~~_#38 could take significant time, depending on the strategy we use. We would like to be able to release to a technical audience first, which is fine with transferring FIL to the Station wallet in order to claim their rewards._~~

```[tasklist]
### Tasks
- [ ] Update Station Website
- [ ] Messaging and internal outreach
- [ ] Airdrops and /or other schemes
- [ ] Spotlight / internal announcements
```

**Comment by juliangruber** [comment]
Since #38 was dropped, we don't need to do an internal soft launch
