### ISSUE TITLE
SPARK CAR checksums

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#42]
eta: 2023-10-15
description: Enhance the SPARK module to compute a checksum of downloaded CAR files. Implement a fraud-detection step that will reject measurements where the checksum disagrees with the majority.

See https://www.notion.so/pl-strflt/SPARK-roadmap-to-LabWeek-23-5d41e603859a4e32908d3c818e3d4542?pvs=4#a00f37b6998b485c9e628604cde3af2e

```[tasklist]
### Tasks
- [ ] Enhance the SPARK module to compute and submit a SHA-512 hash of the CAR file downloaded
- [ ] Add another fraud-detection step to reject measurements with incorrect checksum
- [ ] Update the Grafana dashboard to give us visibility into behaviour of this new feature
```
