### ISSUE TITLE
SMS M1: Meridian Designs Complete, Spark Version Update Fix, Websites Scoped

### ISSUE THREAD

**Issue by coreymjames** [filecoin-station/roadmap#45]
ETA: 2023-09-15

```[tasklist]
### Tasks
- [ ] Meridian contract design frozen 🥶 for v0
- [ ] Ship SPARK autoupdate improvement, enabling faster deployment in the future 
- [ ] Meridian integrates reward function
```
