### ISSUE TITLE
SPARK Public Launch at LabWeek23

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#46]
ETA: 2023-11-08

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-station/roadmap/issues/18
- [ ] https://github.com/filecoin-station/roadmap/issues/41
- [ ] https://github.com/filecoin-station/spark/issues/18
- [ ] https://github.com/filecoin-station/spark/issues/13
- [ ] https://github.com/filecoin-station/spark/issues/11
- [ ] https://github.com/filecoin-station/spark/issues/29
- [ ] https://github.com/filecoin-station/spark/issues/31
```

Starmaps view: https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/46

**Comment by juliangruber** [comment]
BOOM! :)
