### ISSUE TITLE
Automatic Module Updates

### ISSUE THREAD

**Issue by patrickwoodhead** [filecoin-station/roadmap#53]
Currently, when we make an update to the Spark module, we need to ship a new version of Station. This is acceptable while we have one module running on Station, but becomes unacceptable at 2+ modules as there would be an endless stream of new Station apps to download.

Station should listen out for updates to individual modules and then fetch the latest and start running it, without a new version of Station needing to be deployed.

E.g.
- Station v1.7.0 is running Spark v1.9.0
- Spark v1.10.0 is released
- Station v1.7.0 fetches the latest version release
- Station v1.7.0 stops running Spark v1.9.0 and starts running Spark v1.10.0

```[tasklist]
### Tasks
- [x] Core downloads the latest available module version on startup
- [x] Core only runs the module once the download has been attempted
- [x] Core prints useful log events about these downloads
- [x] Core retries downloads for some attempts
- [x] Core periodically checks if there is a new module version available
- [x] Core replaces the running module with the new version after successful download
- [x] Core creates an activity event if the module can't be updated
- [x] Core creates an activity event for fetching the latest source on startup
- [x] Core creates an activity event when it updated the source after startup
```
There's not going to be any downgrade mechanism for the first implementation. We always want users to run the latest versions of every module.

**Comment by bajtos** [comment]
I would like `zinniad` to handle this in the longer term, but we are not there yet.

I think Station Core is the best place to implement this auto-update logic - this way, both Station Core and Station Desktop instances will pick up the updates.

We should think a bit more about the update sequence and edge cases:
- What if we cannot fetch the new SPARK version?
- What if the new SPARK version cannot start?

**Comment by juliangruber** [comment]
Agree that this should be solved at Core level, and eventually move to Zinnia.

For the first version I think we can just always run the latest SPARK version that can be fetched. If it can't be fetched, retry in the next cycle. If it can't start, upgrade once a new version is available. We don't want people to run outdated versions anyway.

We can then use community feedback to steer addition of new features.

**Comment by juliangruber** [comment]
@bajtos I'm happy to take this one, if you want take it let's discuss

**Comment by bajtos** [comment]
> @bajtos I'm happy to take this one, if you want take it let's discuss

Go for it! 🚀 

> Core downloads the latest available module version on startup

Do you want to keep shipping _some_ version of a module bundled inside Station Core, or do you expect Station Core do download all modules when it's started for the first time?

If Station Core is shipped without modules, then we may need to add extra handling for the following error case:
1. User installs Station Desktop (or Station Core)
2. Station Core is not able to download the module
3. There are no modules to run

A few more things to consider:
1. Auto-updating `zinniad` and Bacalhau - is this in scope too?
2. A new Spark version may require features available only in a new Zinnia version. How can we ensure that Station Core does not end up in a broken state with a new Spark version but an old Zinnia version the Spark cannot run on? 
3. How can a Zinnia module like Spark detect that it's running on a Zinnia version it does not support?

**Comment by juliangruber** [comment]
> Do you want to keep shipping some version of a module bundled inside Station Core, or do you expect Station Core do download all modules when it's started for the first time?

I'm thinking no. Since we always want to run the latest versions of modules, if it can't get the latest version we should consider the node not functional. A functional node is one that is able to keep itself updated.

> If Station Core is shipped without modules, then we may need to add extra handling for the following error case:
>
> User installs Station Desktop (or Station Core)
> Station Core is not able to download the module
> There are no modules to run

This could be an activity event! Just like when Core or Zinnia aren't able to run.

> A few more things to consider:
>
> 1. Auto-updating zinniad and Bacalhau - is this in scope too?

Updating Zinnia or Bacalhau isn't a pain point atm, therefore I'm voting to add this later.

> 2.  A new Spark version may require features available only in a new Zinnia version. How can we ensure that Station Core does not end up in a broken state with a new Spark version but an old Zinnia version the Spark cannot run on?

It will end up in a broken state yeah. I think this means we need to ship Desktop/Core updates with new Zinnia versions before updating the module, so that when their installations break we can tell users they need to update the version. I think this is fine - until we add auto updates for Zinnia too.

> 3. How can a Zinnia module like Spark detect that it's running on a Zinnia version it does not support?

It will just fail. I think we need to ensure that Zinnia scripts throwing uncaught errors will create appropriate activity events, so that this error is visible to the user.

**Comment by bajtos** [comment]
> > Do you want to keep shipping some version of a module bundled inside Station Core, or do you expect Station Core do download all modules when it's started for the first time?
> 
> I'm thinking no. Since we always want to run the latest versions of modules, if it can't get the latest version we should consider the node not functional. A functional node is one that is able to keep itself updated.
>
> > If Station Core is shipped without modules, then we may need to add extra handling for the following error case:
> > 
> > User installs Station Desktop (or Station Core)
> > Station Core is not able to download the module
> > There are no modules to run
>
> This could be an activity event! Just like when Core or Zinnia aren't able to run.


SGTM 👍🏻 

I just wanted to flag these edge cases as something to keep in mind during the implementation.

> > 2. A new Spark version may require features available only in a new Zinnia version. How can we ensure that Station Core does not end up in a broken state with a new Spark version but an old Zinnia version the Spark cannot run on?
> 
> It will end up in a broken state yeah. I think this means we need to ship Desktop/Core updates with new Zinnia versions before updating the module, so that when their installations break we can tell users they need to update the version. I think this is fine - until we add auto updates for Zinnia too.

Unfortunately, Stations are slow to pick up new versions. We are likely to end up with a large fraction of our network in a broken state for weeks to months.

I am fine with that, but I'd like us to think through the consequences before we roll out the auto-update feature.

Today's data about Station versions for context:
- Desktop version 1.2.1 was released two weeks ago and more than 50% of our network runs haven't picked it up yet.
- Core version 16.3.1 was released two weeks ago and again, more than 50% of our network haven't picked it up yet.

Station Desktop

|version|pings|
|-|-:|
0.20.4|6
1.0.2|6
1.0.5|12
1.2.0|104
1.2.2|5
1.2.4|92
total|225

Station Core

<img width="137" alt="Screenshot 2024-01-17 at 16 29 30" src="https://github.com/filecoin-station/roadmap/assets/1140553/4945a5ac-51ac-4197-b1f2-336df871adcc">

_Ouch, so many different versions out there!_

> > 3. How can a Zinnia module like Spark detect that it's running on a Zinnia version it does not support?
> 
> It will just fail. I think we need to ensure that Zinnia scripts throwing uncaught errors will create appropriate activity events, so that this error is visible to the user.

Your comments sparked an idea how to approach this:
- Modules should not depend on Zinnia version, but should detect Zinnia features instead. E.g. if Zinnia adds persistence API, a module like Spark should check if the API is available.
- When the module detects that not all required APIs are available, it can log an activity event.

WDTY?

**Comment by juliangruber** [comment]
> Unfortunately, Stations are slow to pick up new versions. We are likely to end up with a large fraction of our network in a broken state for weeks to months.

Wouldn't you say that operators will notice (no earnings) and this incentivise updates instead? I view this as a positive side effect.

> Your comments sparked an idea how to approach this:

> Modules should not depend on Zinnia version, but should detect Zinnia features instead. E.g. if Zinnia adds persistence API, a module like Spark should check if the API is available.
When the module detects that not all required APIs are available, it can log an activity event.
WDTY?

SGTM! Treat Zinnia like a browser, and perform feature detection.
