### ISSUE TITLE
Phase 1: Benchmarking Module PoC

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#58]
```[tasklist]
### Tasks
- [x] Port Arc service worker to Zinnia
- [x] Port opentracing framework
- [x] Only collect benchmark records
- [x] Add field to identify source of benchmarks
- [x] Sync with Saturn team
- [x] Implement feedback
- [x] Adjust items for activity log
- [x] Deploy to Station
```
