### ISSUE TITLE
Scale SPARK PG DB beyond 500 GiB of measurements

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#60]
Fly.io cannot scale storage volumes beyond 500 GiB. We need to find a way how to keep our systems running and have access to historical measurements while using less than 500 GiB by our PG database.

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-station/spark-api/pull/182
- [ ] https://github.com/filecoin-station/spark-api/pull/186
- [ ] https://github.com/filecoin-station/spark-api/pull/187
- [ ] https://github.com/filecoin-station/spark-evaluate/pull/114
```
