### ISSUE TITLE
Link retrievals to miners

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#65]
Currently, SPARK checks the retrieval of CIDs stored in Filecoin but does not know which deal it deal it is testing and which miner is expected to serve the retrieval.

We need to link the retrieval tasks to deals and miners.

There are different ways how to accomplish this.
1. Convert DealProposal data into ContextID string, using the same algorithm as Boost/Frisbii. Then we can filter IPNI response to find the advertisement matching the ContextID of the deal we are testing.
2. Alternatively, we may be able to map provider addresses to miners, but this is less robust.

After a bit of exploration in https://github.com/filecoin-station/fil-deal-context-id/pull/1, I decided to use a different approach:

- Let Spark checkers query the on-chain miner info (method `Filecoin.StateMinerInfo`) to find miner's libp2p identity. This identity should be the same as the identity provided in the IPNI response.

**Tasks**

- [x] Modify [fil-deal-ingester](https://github.com/filecoin-station/fil-deal-ingester) to include MinerID in the data stored in Spark DB.
- [x] Modify spark-api to return MinerID in per-round tasks.
- [x] Modify spark checker to (1) Resolve MinerID to ProviderID (2) filter IPNI response using ProviderID (3) report MinerID and ProviderID in the measurement fields
- [x] Modify spark-api and spark-publish to record & publish MinerID fields
- [x] Modify spark-evaluate to include MinerID in the task/deal id (see https://github.com/filecoin-station/spark-evaluate/pull/143)
- [x] Update spark-evaluate to calculate per-miner stats for each round 
- [x] Expose these stats via spark-stats and visualise them in our internal & public dashboards
- [x] Write a blog post explaining how we solve the problem of determining how to retrieve content stored in a given Filecoin deal

**Cleanup/refactoring opportunities**

- ~~Rename `getTaskId` to `getDealId`, see https://github.com/filecoin-station/spark-evaluate/pull/151#discussion_r1481392027~~

**Out of scope**

- Measure and visualise requests per storage provider → https://github.com/filecoin-station/roadmap/issues/64
- Modify fraud detection (committee building) in spark-evaluate to cross-check ProviderID → https://github.com/filecoin-station/roadmap/issues/59
- Update Spark protocol docs: [CID Sampling](https://filspark.com/cid-sampling) and [Retrieval With Attestation](https://filspark.com/retrieval-attestation)

**Comment by bajtos** [comment]
> Cleanup/refactoring opportunities
> 
> Rename getTaskId to getDealId, see feat: new stat rate_of_deals_advertising_http  spark-evaluate#151 (comment)

I feel the name "task id" better describes the value, so I am going to keep it as it is now.
