### ISSUE TITLE
Contract migration

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#85]
```[tasklist]
### Tasks
- [x] Create infra as code solution for updating the w3name address array from a github file
- [ ] https://github.com/filecoin-station/core/pull/355
- [x] Put a notice in #station/Twitter saying people should upgrade in 7 days
- [ ] After 7 days perform the contract migration and update the contract address array in w3name
```

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/contract-addresses
